// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplicationTest.Models;

#nullable disable

namespace WebApplicationTest.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WebApplicationTest.Models.Conversion", b =>
                {
                    b.Property<int?>("ConversionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("FinalMetric")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<float?>("FinalValue")
                        .HasColumnType("float");

                    b.Property<string>("InitialMetric")
                        .HasColumnType("longtext");

                    b.Property<float?>("InitialValue")
                        .IsRequired()
                        .HasColumnType("float");

                    b.HasKey("ConversionId");

                    b.ToTable("conversions");
                });
#pragma warning restore 612, 618
        }
    }
}
